basePath: /api/v1
definitions:
  CreateAccountRequest:
    properties:
      currency:
        type: string
      owner:
        type: string
    required:
    - currency
    - owner
    type: object
  ListAccountRequest:
    properties:
      pageID:
        minimum: 1
        type: integer
      pageSize:
        maximum: 10
        minimum: 5
        type: integer
    required:
    - pageID
    - pageSize
    type: object
host: localhost:8080
info:
  contact:
    email: rahul.r@i-exceed.com
    name: Iexceed technology solutions
    url: https://www.i-exceed.com/contact-us/
  description: A rest based service in Go using Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://tos.iexceed.dev
  title: Fund transfer Service
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: Responds with the list of all accounts as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ListAccountRequest'
        "400":
          description: Bad/Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get Accounts based on pageId and size
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: Takes a account JSON and store in DB. Return saved JSON.
      parameters:
      - description: Account JSON
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/CreateAccountRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/CreateAccountRequest'
        "400":
          description: Bad/Invalid request
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Create a new account
      tags:
      - accounts
swagger: "2.0"
